import { z } from "zod/v4";

export const funnelEventNameSchema = z.enum([
  "assessment_started",
  "assessment_step_viewed",
  "assessment_step_completed",
  "assessment_step_validation_failed",
  "assessment_resumed",
  "assessment_review_completed",
  "assessment_review_viewed",
  "email_capture_viewed",
  "email_capture_submitted",
  "email_capture_failed",
  "marketing_consent_granted",
  "marketing_consent_declined",
  "assessment_generation_started",
  "assessment_generation_completed",
  "assessment_generation_failed",
  "deterministic_fallback_used",
  "result_access_created",
  "result_email_queued",
  "result_email_sent",
  "result_email_delivered",
  "result_email_delayed",
  "result_email_failed",
  "result_email_bounced",
  "results_viewed",
  "low_ticket_offer_viewed",
  "low_ticket_offer_clicked",
  "checkout_page_viewed",
  "paypal_order_requested",
  "paypal_order_created",
  "paypal_order_creation_failed",
  "paypal_approval_started",
  "paypal_order_approved",
  "paypal_capture_requested",
  "paypal_capture_completed",
  "paypal_capture_pending",
  "paypal_capture_denied",
  "paypal_webhook_received",
  "paypal_webhook_rejected",
  "paypal_webhook_processed",
  "paypal_webhook_failed",
  "purchase_completed",
  "product_entitlement_granted",
  "product_entitlement_failed",
  "product_access_opened",
  "checkout_cancelled",
  "assessment_result_email_queued",
  "assessment_result_email_sent",
  "assessment_result_email_delivered",
  "assessment_result_email_delayed",
  "assessment_result_email_failed",
  "assessment_result_email_bounced",
  "product_access_email_queued",
  "product_access_email_sent",
  "product_access_email_delivered",
  "product_access_email_delayed",
  "product_access_email_failed",
  "product_access_email_bounced",
  "transactional_email_resend_requested",
  "resend_webhook_received",
  "resend_webhook_rejected",
  "resend_webhook_processed",
  "resend_webhook_failed",
]);

export const funnelEventSchema = z.object({
  id: z.string().min(1),
  name: funnelEventNameSchema,
  assessmentId: z.string().min(1).optional(),
  leadId: z.string().min(1).optional(),
  resultId: z.string().min(1).optional(),
  offerSlug: z.string().min(1).optional(),
  purchaseId: z.string().min(1).optional(),
  idempotencyKey: z.string().min(1),
  occurredAt: z.iso.datetime(),
});

export type FunnelEventName = z.infer<typeof funnelEventNameSchema>;
export type FunnelEvent = z.infer<typeof funnelEventSchema>;
