import type { PromptOptions } from "@openuidev/react-lang";
import { incompleteAssessmentOpenUI, standardAssessmentOpenUI, strongAssessmentOpenUI } from "./examples";

export const promptOptions: PromptOptions = {
  preamble: "You compose Local Search Ally contractor assessment presentations. Return only valid OpenUI Lang.",
  additionalRules: [
    "Use AssessmentResults as the root.",
    "Use exactly one AssessmentHeader.",
    "Lead with OpportunityGapHero when a complete estimate exists.",
    "Use IncompleteOpportunityState when a complete estimate does not exist.",
    "Never change the supplied opportunity range.",
    "Never change evidence level or confidence.",
    "Never convert an estimate into a verified fact.",
    "Never call estimated opportunity guaranteed revenue.",
    "Never claim exact calls or jobs were lost.",
    "Display CalculationBreakdown when a complete estimate exists.",
    "Keep assumptions and limitations visible.",
    "Do not render OverallScore.",
    "Do not render CategoryScore or CategoryScoreGrid.",
    "Do not invent a replacement composite score.",
    "Use exactly one PrimaryDiagnosis in a complete assessment.",
    "Use no more than five SupportingFinding components.",
    "Use no more than three PriorityAction components.",
    "Use no more than five QuickWin components.",
    "Use no more than one NextBestStep.",
    "Use no more than one LowTicketOfferCTA.",
    "Show the low-ticket offer no more than once.",
    "Explain findings through diagnosis, evidence, risk, and actions.",
    "Never change supplied deterministic opportunity values, severity, verification, or priority.",
    "Never change offer name, price, deliverables, route, status, product bonuses, or scarcity.",
    "LowTicketOfferCTA may only use an approved offerSlug supplied by the application.",
    "Do not display a purchasable CTA while the offer or product is not publicly ready.",
    "Do not create an offer substitute when no eligible active offer exists.",
    "Never invent evidence, benchmarks, sources, dates, statistics, revenue, rankings, calls, or conversions.",
    "Use cautious language for possible homeowner behavior.",
    "Do not create empty sections.",
    "Do not output markdown, HTML, CSS, JSON, JavaScript, or React.",
    "Return only valid OpenUI Lang.",
  ],
  examples: [standardAssessmentOpenUI, incompleteAssessmentOpenUI, strongAssessmentOpenUI],
  toolCalls: false,
  bindings: false,
};
